package org.launchcode.masyeomasyeo.controllers;

import org.launchcode.masyeomasyeo.models.Artist;
import org.launchcode.masyeomasyeo.models.Genre;
import org.launchcode.masyeomasyeo.models.Song;
import org.launchcode.masyeomasyeo.models.data.ArtistDao;
import org.launchcode.masyeomasyeo.models.data.GenreDao;
import org.launchcode.masyeomasyeo.models.data.SongDao;
import org.launchcode.masyeomasyeo.services.SongService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.Errors;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import java.util.List;
import java.util.Optional;

@Controller // This means that this class is a Controller
public class SongController {

    @Autowired // This means to get the bean called songDao
    // Which is auto-generated by Spring, we will use it to handle the data
    private SongDao songDao;

    @Autowired
    private GenreDao genreDao;

    @Autowired
    private ArtistDao artistDao;

    @Autowired
    private SongService songService;

    @RequestMapping(value = "")
    public String index(Model model) {
        model.addAttribute("songs", songDao.findAll());
        model.addAttribute("genres", genreDao.findAll());
        model.addAttribute("artists", artistDao.findAll());
        model.addAttribute("title","Public Database");

        return "song/index";
    }

    @GetMapping(value = "song/list")
    public ResponseEntity<List<Song>> getAllSongs(
            @RequestParam(defaultValue = "0") Integer pageNo,
            @RequestParam(defaultValue = "10") Integer pageSize,
            @RequestParam(defaultValue = "id") String sortBy)
    {
        List<Song> list = songService.getAllSongs(pageNo, pageSize, sortBy);

        return new ResponseEntity<List<Song>>(list, new HttpHeaders(), HttpStatus.OK);
    }

    @RequestMapping(value = "song/add", method = RequestMethod.GET)
    public String displayAddSongForm(Model model) {
        model.addAttribute("title", "Add Song");
        model.addAttribute(new Song());
        model.addAttribute("genres", genreDao.findAll());
        model.addAttribute("artists", artistDao.findAll());
        return "song/add";
    }

    @PostMapping(value = "song/add") // Map ONLY POST Requests
    public String processAddSongForm(Model model, @ModelAttribute @Valid Song newSong,
                      Errors errors, @RequestParam int[] genre_id,
                      @RequestParam int[] artist_id) {

        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        if (errors.hasErrors()) {
            model.addAttribute("title", "Add Song");
            model.addAttribute(new Song());
            model.addAttribute("genres", genreDao.findAll());
            model.addAttribute("artists", artistDao.findAll());
            return "song/add";
        }

        for (int artistId : artist_id) {
            Artist art = artistDao.findById(artistId).orElse(null);
            newSong.getArtists().add(art);
        }
        for (int genreId : genre_id) {
            Genre aGen = genreDao.findById(genreId).orElse(null);
            newSong.getGenres().add(aGen);
        }

        songDao.save(newSong);
        System.out.println(newSong);
        System.out.println(songDao.findAll());
        return "redirect:";
    }


}
